apiVersion: batch/v1
kind: CronJob
metadata:
  name: thread-dump-cronjob
  namespace: fes
spec:
  schedule: "*/3 * * * *" #every 5th minutes
  successfulJobsHistoryLimit: 3 
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: thread-dump-sa
          imagePullSecrets:
            - name: acr-credential
          containers:
            - name: my-cronjob
              image: fareye.azurecr.io/alertbots:dev_bca3f3ba0
              imagePullPolicy: IfNotPresent
              command: [ "/bin/bash" ]
              args: [ "/etc/config/thread_dump_cronjob.sh" ]
          volumes:
            - name: thread-dump-cronjob-script
              configMap:
                name: thread-dump-cronjob-script-config
          restartPolicy: Never
